### ISSUE TITLE
大佬你好，想请教下你实验里面的三个EUVP数据集分别是如何划分的

### ISSUE THREAD

**Issue by Chengkai66** [YuZhao1999/awesome-underwater-image-enhancement#1]
EUVP-D、EUVP-I、和EUVP-S的训练和测试集对应的是如何划分的嘞

**Comment by YuZhao1999** [comment]
参考官网https://irvlab.cs.umn.edu/resources/euvp-dataset

**Comment by YuZhao1999** [comment]
> EUVP-D、EUVP-I、和EUVP-S的训练和测试集对应的是如何划分的嘞
参考官网https://irvlab.cs.umn.edu/resources/euvp-dataset

**Comment by Chengkai66** [comment]
哈哈，谢谢佬的回复，之前查资料找到了
